force-app/main/default/objects/Slackbot_Token__mdt/Slackbot_Token__mdt.object-meta.xml
<CustomObject>
    <label>Slackbot Token</label>
    <pluralLabel>Slackbot Tokens</pluralLabel>
</CustomObject>

force-app/main/default/objects/Slackbot_Token__mdt/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PostToSlack.cls
public with sharing class PostToSlack {
    public class slackRequest { 
        @InvocableVariable(label='Slack Message' required=true) 
        public String slackMessage; 
        @InvocableVariable(label='Channel/User to post to' required=true) 
        public String channel; 
    }

    @InvocableMethod(label='Post to Slack')
    public static void publishToSlack(List<slackRequest> requests) {
        Slackbot_Token__mdt token = [
            SELECT Token__c, DeveloperName
            FROM Slackbot_Token__mdt
            WHERE DeveloperName = 'Request_Compensation_Bot'
            LIMIT 1
        ];

        for(slackRequest r:requests){
            String bearer = 'Bearer ' + token.Token__c;        
            String message = EncodingUtil.urlEncode(r.slackMessage, 'UTF-8');

            HttpRequest req = new HttpRequest();
            req.setEndpoint('https://slack.com/api/chat.postMessage?channel=' + r.channel + '&text=' + message + '&pretty=1');
            req.setMethod('POST');
            req.setHeader('Authorization', bearer);
            Http http = new Http();
            HttpResponse res = http.send(req);
        } 
    }
}